services:
  - type: web
    name: college-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
